/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469.0 */
/* Module Version: 5.7 */
/* Sat Dec  5 17:38:09 2020 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ), .LOCK( ));
